eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost



spring:
    jpa:
        hibernate:
            naming:
                physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
                implicit-strategy: 'org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl'
            ddl-auto: 'update'

feign:
    client:
        config:
            default:
                connectTimeout: '5000'
                readTimeout: '5000'
